import test from 'node:test';import assert from 'node:assert/strict';import {handleApi} from '../server/magi.js';
const fakeKey='TEST-SECRET-MAGI-0123456789';
class Bucket{data=new Map();async get(k){const v=this.data.get(k);return v?{json:async()=>JSON.parse(v)}:null}async put(k,v){this.data.set(k,v)}async delete(k){this.data.delete(k)}}
function env(){return{BUCKET:new Bucket(),MAGI_VAULT_KEY:Buffer.alloc(32,7).toString('base64')}}
function req(path,method='GET',data,user='owner',origin='https://magi.test'){return new Request('https://magi.test'+path,{method,headers:{...(user?{'oai-authenticated-user-id':user}:{}),...(method!=='GET'?{'origin':origin,'content-type':'application/json'}:{})},body:data?JSON.stringify(data):undefined})}
async function save(e,user='owner',provider='gemini'){return handleApi(req('/api/providers','PUT',{provider,apiKey:fakeKey,model:provider==='gemini'?'gemini-3.1-flash-lite-preview':'gpt-4.1-mini'},user),e)}
test('authentication and CSRF fail closed',async()=>{const e=env();assert.equal((await handleApi(req('/api/providers','GET',null,null),e)).status,401);assert.equal((await handleApi(req('/api/providers','PUT',{provider:'gemini',apiKey:fakeKey},'owner','https://evil.test'),e)).status,403);assert.equal(e.BUCKET.data.size,0)});
test('encrypted server storage, metadata-only response, and per-user separation',async()=>{const e=env();const result=await save(e);assert.equal(result.status,200);const response=await result.text();assert(!response.includes(fakeKey));assert(!JSON.stringify([...e.BUCKET.data.values()]).includes(fakeKey));const status=await(await handleApi(req('/api/providers'),e)).json();assert.equal(status.active,'gemini');assert.equal(status.providers[0].configured,true);const other=await(await handleApi(req('/api/providers','GET',null,'other'),e)).json();assert.equal(other.active,'mock');assert.equal(other.providers[0].configured,false);await handleApi(req('/api/providers','DELETE',{provider:'gemini'},'other'),e);assert.equal((await(await handleApi(req('/api/providers'),e)).json()).providers[0].configured,true);await handleApi(req('/api/providers','DELETE',{provider:'gemini'}),e);assert.equal((await(await handleApi(req('/api/providers'),e)).json()).providers[0].configured,false)});
test('tampering and missing encryption key fail safely',async()=>{const e=env();await save(e);e.MAGI_VAULT_KEY=Buffer.alloc(32,9).toString('base64');const r=await handleApi(req('/api/providers'),e);assert.equal(r.status,503);assert(!(await r.text()).includes(fakeKey));const r2=await save({BUCKET:new Bucket()});assert.equal(r2.status,503)});
test('unknown provider and injection model rejected before external call',async()=>{const e=env();assert.equal((await handleApi(req('/api/providers','PUT',{provider:'evil',apiKey:fakeKey,endpoint:'https://evil.test'}),e)).status,400);assert.equal((await handleApi(req('/api/providers','PUT',{provider:'gemini',apiKey:fakeKey,model:'../secret?key=foo'}),e)).status,400)});
test('provider errors never expose body or key',async()=>{const e=env();await save(e);const old=globalThis.fetch;globalThis.fetch=async()=>new Response('Vendor debug '+fakeKey,{status:401});try{const r=await handleApi(req('/api/providers/test','POST',{provider:'gemini'}),e);assert.equal(r.status,400);assert(!(await r.text()).includes(fakeKey))}finally{globalThis.fetch=old}});
test('four real provider calls, progress, structured verdict, no secret in prompt or response',async()=>{const e=env();await save(e);const old=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});assert.equal(new URL(url).hostname,'generativelanguage.googleapis.com');assert.equal(options.redirect,'error');assert.equal(options.headers['x-goog-api-key'],fakeKey);assert(!options.body.includes(fakeKey));return Response.json({candidates:[{content:{parts:[{text:JSON.stringify({verdict:'APPROVE_WITH_CHANGES',score:82,summary:'AI evaluation '+fakeKey,reasons:['根拠'],concerns:['懸念'],recommendations:['提案'],minorityReport:{core:'MELCHIOR',reason:'別案を検討'}})}]}}]})};try{const response=await handleApi(req('/api/decide','POST',{question:'実装方式を比較してください',category:'技術相談'}),e);assert.equal(response.status,200);const raw=await response.text();assert(!raw.includes(fakeKey));const events=raw.trim().split('\n').map(JSON.parse);assert.equal(calls.length,4);assert.deepEqual(events.filter(e=>e.type==='step').map(e=>e.step),[0,1,2,3,4,5]);const d=events.at(-1).decision;assert.equal(d.live,true);assert.equal(d.verdict,'APPROVE_WITH_CHANGES');assert.equal(d.cores.length,3);assert.equal(d.minorityReport.core,'MELCHIOR')}finally{globalThis.fetch=old}});
test('OpenAI-compatible credentials use only fixed vendor host',async()=>{const e=env();await save(e,'owner','openai');const old=globalThis.fetch;let calls=0;globalThis.fetch=async(url,o)=>{calls++;assert.equal(url,'https://api.openai.com/v1/chat/completions');assert.equal(o.headers.authorization,'Bearer '+fakeKey);return Response.json({choices:[{message:{content:'接続成功'}}]})};try{const r=await handleApi(req('/api/providers/test','POST',{provider:'openai',endpoint:'https://evil.test'}),e);assert.equal(r.status,200);assert.equal(calls,1);assert(!(await r.text()).includes(fakeKey))}finally{globalThis.fetch=old}});
test('invalid AI payload does not become a successful verdict',async()=>{const e=env();await save(e);const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({candidates:[{content:{parts:[{text:'{"verdict":"APPROVE"}'}]}}]});try{const r=await handleApi(req('/api/decide','POST',{question:'判断してください'}),e);const events=(await r.text()).trim().split('\n').map(JSON.parse);assert(events.some(e=>e.type==='error'));assert(!events.some(e=>e.type==='result'))}finally{globalThis.fetch=old}});
