import React from 'react';
import {Home,MessageSquarePlus,History,UserRound,Settings,Activity,FileText,SlidersHorizontal,Menu,ChevronRight,ArrowRight,Paperclip,Check,Cloud,ChevronDown,Search,X} from 'lucide-react';
export const cores=[{name:'CASPAR',sub:'ANALYSIS CORE',jp:'分析・検証',score:82,color:'var(--cyan)'},{name:'MELCHIOR',sub:'CREATIVE CORE',jp:'創造・未来',score:76,color:'var(--amber)'},{name:'BALTHASAR',sub:'HUMANITY CORE',jp:'人間・現実',score:88,color:'var(--ice)'}];
export const nav=[{id:'home',label:'ホーム',icon:Home},{id:'consult',label:'新しい相談',icon:MessageSquarePlus},{id:'history',label:'履歴',icon:History},{id:'profile',label:'プロフィール',icon:UserRound},{id:'providers',label:'AI設定',icon:SlidersHorizontal},{id:'diagnostics',label:'システム診断',icon:Activity},{id:'docs',label:'ドキュメント',icon:FileText},{id:'settings',label:'設定',icon:Settings}];
export function Brand(){return <div className="brand"><div><span>KAZU</span><b>MAGI SYSTEM</b></div><small>TRINITY DECISION CORE</small></div>}
export function Sidebar({page,navigate,open,close}){return <><div className={`nav-scrim ${open?'visible':''}`} onClick={close}/><aside className={`sidebar ${open?'open':''}`}><Brand/><p className="brand-copy">考え、つなぎ、<br/>よりよい未来をつくる。<span>for Kazu</span></p><button className="mobile-close icon-button" onClick={close} aria-label="メニューを閉じる"><X size={20}/></button><nav aria-label="メインナビゲーション">{nav.map(({id,label,icon:Icon},i)=><button key={id} className={`${page===id?'selected':''} ${i===6?'nav-separator':''}`} aria-current={page===id?'page':undefined} onClick={()=>navigate(id)}><Icon size={18}/><span>{label}</span>{page===id&&<ChevronRight className="nav-chevron" size={13}/>}</button>)}</nav><div className="sidebar-landscape"><div className="horizon"/><div className="island"/><p>Same Dreams.<br/>A Brighter Tomorrow.</p><strong>THINK DEEPLY.<br/>SEE WIDELY.<br/>DECIDE WISELY.</strong><small>PERSONAL DECISION INTELLIGENCE</small></div></aside></>}
export function MagiHeader({now,onMenu,navigate}){return <header className="magi-header"><div className="mobile-brand"><Brand/></div><div className="header-section"><span className="connection"><i/> SYSTEM ONLINE</span><span className="header-divider"/><span className="date">{now.toLocaleDateString('sv-SE').replaceAll('-','.')} <b>{now.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</b></span></div><div className="header-actions"><button className="icon-button settings-top" aria-label="設定を開く" onClick={()=>navigate('settings')}><Settings size={18}/></button><button className="icon-button" aria-label="メニューを開く" onClick={onMenu}><Menu size={22}/></button></div></header>}
export function CoreChamber({step,running,calls,activeProvider}){return <section className="core-chamber" aria-label="CASPAR、MELCHIOR、BALTHASAR 巨大演算コア"><div className="chamber-image"/><div className="chamber-vignette"/><div className="chamber-topline"><span><i/> TRINITY CORE // STANDBY</span><span>SECTOR 07 · KAZU LAB</span></div><div className="core-labels">{cores.map((c,i)=><div className={`core-label ${running&&step===i+1?'processing':''}`} key={c.name} style={{'--core-color':c.color}}><span className="core-number">0{i+1}</span><h2>{c.name}</h2><div className="core-light"/><small>{c.sub}</small><p>{c.jp}</p><span className="core-live"><i/>{running&&step===i+1?'PROCESSING':'CORE ONLINE'}</span></div>)}</div><div className="hero-side"><p className="philosophy">正しい答えではなく、<br/><strong>よりよい選択を。</strong></p><ProviderStatus calls={calls} activeProvider={activeProvider}/></div><div className="chamber-caption"><span>三つの知性。一つの、よりよい選択。</span><span>CASPAR × MELCHIOR × BALTHASAR</span></div></section>}
export function ProviderStatus({calls,activeProvider='mock'}){return <section className="free-panel panel"><div className="panel-heading"><span>TODAY STATUS</span><span className="free-badge">{activeProvider==='mock'?'FREE MODE':'API MODE'}</span></div><div className="calls-title">AI CALLS TODAY <span>{calls} <small>/ 50</small></span></div><div className="usage-track"><i style={{width:Math.min(calls*2,100)+'%'}}/></div><dl><div><dt><i className="provider-dot local"/>Local</dt><dd>—</dd></div><div><dt><i className="provider-dot gemini"/>Gemini Free</dt><dd>—</dd></div><div><dt><i className="provider-dot external"/>External</dt><dd>0</dd></div><div><dt><i className="provider-dot mock"/>{activeProvider==='mock'?'Mock / Demo':activeProvider}</dt><dd>{calls}</dd></div></dl><div className="cost"><span>COST</span><b>{activeProvider==='mock'?'¥0':'API料金'} <small>{activeProvider==='mock'?'/ day':'契約に従う'}</small></b></div></section>}
export const categories=['技術相談','購入判断','企画アイデア','比較検討','リスク評価','その他'];
export function ConsultationPanel({text,setText,category,setCategory,execute,running,inputRef,files,onFiles,onRemove}){return <section className="consultation panel"><form onSubmit={e=>{e.preventDefault();execute()}}><label htmlFor="consultation-input" className="sr-only">相談したいこと</label><textarea ref={inputRef} id="consultation-input" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();execute()}}} placeholder="相談したいことを入力してください..." required maxLength={5000}/><div className="input-actions"><span className="input-hint">YOUR QUESTION. THREE PERSPECTIVES.</span><label className="attachment-button" title="ファイルを添付"><Paperclip size={18}/><span className="sr-only">ファイルを添付</span><input type="file" multiple onChange={onFiles} accept=".txt,.md,.json,.csv"/></label><button className="execute" type="submit" disabled={running}>{running?'演算中':'実行'}<ArrowRight size={17}/></button></div></form>{files.length>0&&<div className="attachments">{files.map((f,i)=><button key={i} onClick={()=>onRemove(i)}>{f.name}<X size={12}/></button>)}</div>}<div className="quick-categories" aria-label="相談カテゴリー">{categories.map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}><span>#</span> {c}</button>)}<span className="shortcut">⌘ / Ctrl + Enter</span></div></section>}
export const steps=[['CONTEXT','コンテキスト解析'],['CASPAR','分析'],['MELCHIOR','検討'],['BALTHASAR','評価'],['CONSENSUS','統合・検証'],['FINAL','最終決議']];
export function ProcessingTimeline({step,running,finished}){return <section className="timeline panel"><div className="panel-heading"><h3>処理ステータス</h3><span className="sequence-label">{running?'MAGI DECISION SEQUENCE':finished?'FINAL VERDICT · COMPLETE':'AWAITING INPUT'}</span></div><ol>{steps.map(([en,jp],i)=><li key={en} className={`${running&&step===i?'current':''} ${finished||running&&step>i?'done':''}`}><div className="step-line"><span>{finished||step>i?<Check size={13}/>:i+1}</span><i/><ArrowRight size={12}/></div><b>{en}</b><p>{jp}</p><small>{running&&step===i?'PROCESSING…':finished||running&&step>i?'COMPLETE':'STANDBY'}</small></li>)}</ol><div className="mobile-processing" role="status">{running?`${steps[step][0]} — ${steps[step][1]}`:finished?'FINAL VERDICT — 最終決議完了':'TRINITY CORE — 相談を待機中'}</div></section>}
export function CoreScoreCard({core,score}){return <div className="score-card" style={{'--core-color':core.color}}><h4>{core.name}</h4><small>{core.jp}</small><div className="score-meter"><svg viewBox="0 0 100 100" aria-hidden="true"><circle className="meter-track" cx="50" cy="50" r="41"/><circle className="meter-value" cx="50" cy="50" r="41" strokeDasharray={`${score*2.576} 258`}/></svg><b>{score}<span>%</span></b></div><div className="meter-bars" aria-hidden="true">{[15,23,28,34,41,49,55,62,70].map((h,i)=><i style={{height:h+'%',opacity:.4+i*.065}} key={h}/>)}</div></div>}
export function CoreScores({scores}){return <section className="scores-panel panel"><div className="panel-heading"><h3>3つの視点</h3><span>CORE EVALUATION</span></div><div className="core-scores">{cores.map((core,i)=><CoreScoreCard key={core.name} core={core} score={scores[i]}/>)}</div></section>}
export function ConsensusPanel({decision,running}){return <section data-verdict={decision.verdict} className={`consensus panel ${running?'building':''}`}><span>MAGI CONSENSUS</span><div className="consensus-orbit"><strong>{running?'BUILDING':decision.verdict}</strong></div><b>{running?'—':decision.confidence}<small>%</small></b><p>{running?'三つの視点を統合中':'三基の合議による総合判断'}</p></section>}
export function DecisionCard({decision,onOpen}){return <section className="decision-panel panel" data-verdict={decision.verdict}><div className="panel-heading"><h3>最新の決議</h3><time>{decision.date}</time></div><button className="decision-card" onClick={()=>onOpen(decision)}><span className="verdict-label"><i/>{decision.verdict}</span><strong>{decision.title}</strong><p>{decision.summary}</p><span className="view-detail">詳細を見る <ArrowRight size={14}/></span></button></section>}
export function TopicList({decisions,onOpen}){return <section className="topics-panel panel"><div className="panel-heading"><h3>最近のトピック</h3><History size={14}/></div><ul>{decisions.slice(0,5).map(d=><li key={d.id}><button onClick={()=>onOpen(d)}><span>{d.title}</span><time>{d.date.slice(5)}</time></button></li>)}</ul><div className="topics-foot"><i/> ALL DECISIONS SYNCED LOCALLY</div></section>}
export function BottomNavigation({page,navigate}){return <nav className="bottom-nav" aria-label="モバイルナビゲーション">{[{id:'home',label:'ホーム',icon:Home},{id:'history',label:'履歴',icon:History},{id:'consult',label:'相談',icon:MessageSquarePlus},{id:'profile',label:'プロフィール',icon:UserRound},{id:'settings',label:'設定',icon:Settings}].map(({id,label,icon:Icon})=><button key={id} className={`${page===id?'selected':''} ${id==='consult'?'central-nav':''}`} onClick={()=>navigate(id)} aria-label={label} aria-current={page===id?'page':undefined}>{id==='consult'?<span className="energy-node"><i/><svg viewBox="0 0 40 40"><path d="M20 3 35 12 35 28 20 37 5 28 5 12Z M20 3 20 37 M5 12 35 28 M35 12 5 28 M5 12 20 20 35 12 M5 28 20 20 35 28"/></svg></span>:<Icon size={20}/>}<span>{label}</span></button>)}</nav>}
