import http from 'node:http';
import {mkdir,readFile,writeFile,rename,unlink} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
import {handleApi} from '../server/magi.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const production=process.argv.includes('--production');
const port=Number(process.env.PORT||5173);if(!Number.isInteger(port)||port<1||port>65535)throw new Error('PORT must be 1–65535.');
const dataDir=process.env.MAGI_LOCAL_DATA_DIR||path.join(root,'.magi-local');await mkdir(dataDir,{recursive:true,mode:0o700});
const keyFile=path.join(dataDir,'vault.key');let vaultKey;try{vaultKey=(await readFile(keyFile,'utf8')).trim()}catch(e){if(e.code!=='ENOENT')throw e;vaultKey=randomBytes(32).toString('base64');await writeFile(keyFile,vaultKey,{mode:0o600,flag:'wx'})}
const objectPath=key=>{if(!/^[a-zA-Z0-9/_\-.]+$/.test(key)||key.includes('..'))throw new Error('Invalid storage path');return path.join(dataDir,'objects',key)};
const bucket={async get(key){try{const value=await readFile(objectPath(key),'utf8');return{json:async()=>JSON.parse(value)}}catch(e){if(e.code==='ENOENT')return null;throw e}},async put(key,value){const file=objectPath(key);await mkdir(path.dirname(file),{recursive:true,mode:0o700});const tmp=file+'.'+randomBytes(6).toString('hex')+'.tmp';await writeFile(tmp,value,{mode:0o600});await rename(tmp,file)},async delete(key){try{await unlink(objectPath(key))}catch(e){if(e.code!=='ENOENT')throw e}}};
const env={BUCKET:bucket,MAGI_VAULT_KEY:vaultKey};
const nonce=randomBytes(18).toString('base64');
const vite=production?null:await(await import('vite')).createServer({root,html:{cspNonce:nonce},server:{middlewareMode:true,hmr:{host:'127.0.0.1',port:port+1},fs:{deny:['.env','.env.*','**/.git/**','**/.magi-local/**','**/*.pem','**/*.key']}},appType:'spa'});
const security={'x-content-type-options':'nosniff','referrer-policy':'no-referrer','content-security-policy':`default-src 'self'; script-src 'self' 'nonce-${nonce}'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' ws://127.0.0.1:* ws://localhost:*; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'`};
const server=http.createServer(async(req,res)=>{try{const host=req.headers.host;const allowed=new Set(['localhost:'+port,'127.0.0.1:'+port,'[::1]:'+port]);if(!allowed.has(host)){res.writeHead(403);res.end('Local access only');return}const url=new URL(req.url,'http://'+host);let decoded;try{decoded=decodeURIComponent(url.pathname)}catch{res.writeHead(400);res.end();return}if(decoded.includes('.magi-local')||decoded.includes('.git')||decoded.includes('.env')||decoded.includes('vault.key')){res.writeHead(404);res.end('Not found');return}for(const[k,v]of Object.entries(security))res.setHeader(k,v);
if(url.pathname.startsWith('/api/')){if(req.headers['sec-fetch-site']==='cross-site'){res.writeHead(403);res.end('Cross-site request rejected');return}const parts=[];let size=0;for await(const c of req){size+=c.length;if(size>80000){res.writeHead(413);res.end('Payload too large');return}parts.push(c)}const headers=new Headers(req.headers);headers.set('oai-authenticated-user-id','local-owner');const request=new Request(url,{method:req.method,headers,body:['GET','HEAD'].includes(req.method)?undefined:Buffer.concat(parts)});const response=await handleApi(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));if(response.body){const reader=response.body.getReader();while(true){const r=await reader.read();if(r.done)break;res.write(Buffer.from(r.value))}}res.end();return}
if(vite){vite.middlewares(req,res,()=>{res.writeHead(404);res.end()});return}if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return}const target=path.resolve(root,'dist','.'+decoded);if(target!==path.join(root,'dist')&&!target.startsWith(path.join(root,'dist')+path.sep)){res.writeHead(404);res.end();return}const file=decoded==='/'?path.join(root,'dist','index.html'):target;if(file.includes(path.sep+'server'+path.sep)||file.includes('.openai')){res.writeHead(404);res.end();return}try{const bytes=await readFile(file);res.setHeader('content-type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(req.method==='HEAD'?undefined:bytes)}catch{res.writeHead(404);res.end('Not found')}}catch{res.writeHead(500);res.end('Local server error')}});
server.listen(port,'127.0.0.1',()=>console.log(`KAZU MAGI SYSTEM — http://localhost:${port}\nAPI keys are encrypted in .magi-local/ (never served to the browser).`));
async function stop(){server.close();await vite?.close();process.exit(0)}process.on('SIGINT',stop);process.on('SIGTERM',stop);
